import { Image, Map, Text, Textarea, View } from "@tarojs/components";
import Taro, { useLoad } from "@tarojs/taro";
import { useState } from "react";
import { StatePanel } from "@/components";
import { routeService } from "@/services/routes";
import { userRouteService } from "@/services/user-routes";
import { useUserStore } from "@/stores/user-store";
import type { RouteComment, UserRoute } from "@/types/api";
import { openLogin } from "@/utils/login-return";
import { uploadImage } from "@/utils/upload";
import "../user-routes.scss";
import "../../../packageRoutes/pages/detail/index.scss";

export default function UserRouteDetailPage() {
  const [route, setRoute] = useState<UserRoute>(); const [comments, setComments] = useState<RouteComment[]>([]); const [text, setText] = useState(""); const [images, setImages] = useState<string[]>([]); const [state, setState] = useState<"loading"|"ready"|"error">("loading"); const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState(false);
  const load = async (id: string) => { try { const detail = await userRouteService.detail(id); setRoute(detail); if (detail.visibility === 2) setComments((await userRouteService.comments(id)).items); setState("ready"); } catch { setState("error"); } };
  useLoad((options) => { useUserStore.getState().hydrate(); if (options.id) void load(options.id); else setState("error"); });
  const addImage = async () => { if (uploading) return; if (images.length >= 2) return void Taro.showToast({ title: "最多上传 2 张图片", icon: "none" }); try { const selected = await Taro.chooseImage({ count: 2 - images.length, sizeType: ["compressed"], sourceType: ["album", "camera"] }); setUploading(true); const uploaded: string[] = []; for (const path of selected.tempFilePaths) uploaded.push(await uploadImage(path, "image/jpeg", "route-comments")); setImages([...images, ...uploaded].slice(0, 2)); } catch (error) { Taro.showToast({ title: error instanceof Error ? error.message : "上传失败", icon: "none" }); } finally { setUploading(false); } };
  const submit = async () => { if (saving || uploading) return; if (!route || text.trim().length < 2) return void Taro.showToast({ title: "请输入至少2个字", icon: "none" }); if (!useUserStore.getState().isLoggedIn) return void openLogin(`/pages/routes/detail/index?id=${route.id}`); setSaving(true); try { const created = await userRouteService.createComment(route.id, text.trim(), images, `user-route-comment-${Date.now()}`); setComments([created, ...comments]); setText(""); setImages([]); Taro.showToast({ title: "评论已发布", icon: "success" }); } catch (error) { Taro.showToast({ title: error instanceof Error ? error.message : "发布失败", icon: "none" }); } finally { setSaving(false); } };
  const report = async (comment: RouteComment) => { if (!useUserStore.getState().isLoggedIn) return void openLogin(`/pages/routes/detail/index?id=${route?.id}`); const result = await Taro.showModal({ title: "举报评论", content: "确认举报该评论？" }); if (!result.confirm) return; try { await routeService.reportComment(comment.id); Taro.showToast({ title: "举报已提交", icon: "success" }); } catch (error) { Taro.showToast({ title: error instanceof Error ? error.message : "举报失败", icon: "none" }); } };
  const removeComment = async (comment: RouteComment) => { const result = await Taro.showModal({ title: "删除评论", content: "确认删除这条评论？" }); if (!result.confirm) return; try { await routeService.deleteComment(comment.id); setComments(comments.filter((item) => item.id !== comment.id)); Taro.showToast({ title: "已删除", icon: "success" }); } catch (error) { Taro.showToast({ title: error instanceof Error ? error.message : "删除失败", icon: "none" }); } };
  const remove = async () => { if (!route) return; const result = await Taro.showModal({ title: "删除路线", content: "删除后无法恢复，确认删除？" }); if (result.confirm) { await userRouteService.remove(route.id); Taro.showToast({ title: "已删除", icon: "success" }); setTimeout(() => Taro.navigateBack(), 400); } };
  if (state === "loading") return <View className="user-route-page"><StatePanel type="loading" title="正在加载路线" /></View>; if (state === "error" || !route) return <View className="user-route-page"><StatePanel type="error" title="路线不存在或无权查看" /></View>;
  const points = [{ latitude: route.start_lat, longitude: route.start_lng }, ...route.waypoints, ...(route.end_lat != null && route.end_lng != null ? [{ latitude: route.end_lat, longitude: route.end_lng }] : [])];
  const pointItems = [{ name: route.start_location, type: "起点", latitude: route.start_lat, longitude: route.start_lng }, ...route.waypoints.map((point) => ({ ...point, type: "途经" })), ...(route.end_location && route.end_lat != null && route.end_lng != null ? [{ name: route.end_location, type: "终点", latitude: route.end_lat, longitude: route.end_lng }] : [])];
  const favorite = async () => { if (!useUserStore.getState().isLoggedIn) return void openLogin(`/pages/routes/detail/index?id=${route.id}`); await userRouteService.favorite(route.id); setRoute({ ...route, is_favorited: true, favorite_count: route.favorite_count + (route.is_favorited ? 0 : 1) }); Taro.showToast({ title: "已收藏", icon: "success" }); };
  return <View className="route-detail">
    {route.images[0] ? <Image className="route-detail__cover" mode="aspectFill" src={route.images[0]} /> : null}
    <View className="route-detail__header"><Text className="route-detail__title">{route.title}{route.visibility === 1 ? <Text className="user-route-private">私密</Text> : null}</Text><Text className="route-detail__meta">{route.start_location} → {route.end_location || "未设置终点"} · {route.creator.nickname}</Text><View className="route-detail__facts"><Text>{route.total_distance ?? "-"} km</Text><Text>约 {route.estimated_time ?? "-"} 分钟</Text><Text>难度 {route.difficulty ? "★".repeat(route.difficulty) : "待补充"}</Text></View>{route.visibility === 2 ? <Text className="route-detail__meta">浏览 {route.view_count} · 收藏 {route.favorite_count}</Text> : null}</View>
    <View className="route-detail__section"><Text className="route-detail__heading">地图与点位</Text>{points.length ? <Map className="route-detail__map" latitude={route.start_lat} longitude={route.start_lng} markers={points.map((point, index) => ({ id: index + 1, latitude: point.latitude, longitude: point.longitude, width: 24, height: 24, iconPath: "/assets/tabbar/route-selected.png" }))} onError={() => undefined} /> : <View className="route-detail__map-fallback">地图暂不可用</View>}<View className="route-detail__points">{pointItems.map((point, index) => <View key={`${point.latitude}-${point.longitude}-${index}`} className="route-detail__point"><Text className="route-detail__point-order">{index + 1}</Text><View><Text className="route-detail__point-name">{point.name}</Text><Text className="route-detail__point-meta">{point.type}</Text></View></View>)}</View></View>
    <View className="route-detail__section"><Text className="route-detail__heading">路线说明</Text><Text className="route-detail__copy">{route.description || "暂无路线简介"}</Text>{route.images.length ? <View className="user-route-gallery">{route.images.map((url) => <Image key={url} src={url} mode="aspectFill" onClick={() => Taro.previewImage({ current: url, urls: route.images })} />)}</View> : null}</View>
    <View className="route-detail__safety"><Text className="route-detail__heading">安全提示</Text><Text>路线信息由用户录入，仅供行程参考。出发前请复核天气、道路状况和车辆状态，全程佩戴头盔并遵守交通法规。</Text></View>
    {route.visibility === 2 ? <View className="route-detail__section"><Text className="route-detail__heading">骑友评论</Text><Textarea className="route-detail__comment-input" value={text} maxlength={500} placeholder="分享这条路线的体验（2-500 字）" onInput={(e) => setText(e.detail.value)} /><View className="route-detail__comment-images">{images.map((url, index) => <View key={url} className="route-detail__comment-image-wrap"><Image className="route-detail__comment-image" src={url} mode="aspectFill" /><Text className="route-detail__comment-image-remove" onClick={() => setImages(images.filter((_, i) => i !== index))}>×</Text></View>)}{images.length < 2 ? <View className="route-detail__comment-image-add" onClick={() => void addImage()}><Text>{uploading ? "上传中…" : "+ 图片"}</Text><Text>最多2张</Text></View> : null}</View><View className="route-detail__comment-actions"><Text className="route-detail__comment-count">{text.length}/500</Text><View className="route-detail__comment-submit" onClick={() => void submit()}>{saving ? "发布中…" : "发表评论"}</View></View>{comments.length ? comments.map((comment) => <View key={comment.id} className="route-detail__ride route-detail__comment"><View className="route-detail__comment-body"><Text className="route-detail__ride-title">{comment.author.nickname}</Text><Text className="route-detail__ride-meta">{comment.content}</Text>{comment.images.length ? <View className="route-detail__comment-gallery">{comment.images.map((url) => <Image key={url} className="route-detail__comment-gallery-image" src={url} mode="aspectFill" onClick={() => Taro.previewImage({ current: url, urls: comment.images })} />)}</View> : null}<View className="route-detail__comment-footer"><Text onClick={() => comment.author.id !== useUserStore.getState().user?.id ? void report(comment) : void removeComment(comment)}>{comment.author.id !== useUserStore.getState().user?.id ? "举报" : "删除"}</Text></View></View></View>) : <Text className="route-detail__copy">还没有公开评论，来发表第一条吧</Text>}</View> : null}
    <View className="route-detail__create-ride" onClick={() => Taro.navigateTo({ url: `/pages/rides/create/index?routeSource=user&routeId=${route.id}` })}>按此路线发起同行</View>
    <Text className="route-detail__updated">信息更新于 {new Date(route.updated_at).toLocaleDateString()}，出发前请再次核对路线。</Text>
    <View className="route-detail__bottom">{route.is_owner ? <><View className="route-detail__favorite" onClick={() => void remove()}>删除路线</View><View className="route-detail__primary" onClick={() => Taro.navigateTo({ url: `/pages/routes/create/index?id=${route.id}` })}>编辑路线</View></> : <View className="route-detail__primary" onClick={() => void favorite()}>{route.is_favorited ? "★ 已收藏" : "☆ 收藏路线"}</View>}</View>
  </View>;
}
