import { Image, Input, Text, View } from "@tarojs/components";
import Taro, { useDidShow, usePullDownRefresh } from "@tarojs/taro";
import { useState } from "react";
import { StatePanel } from "@/components";
import { userRouteService } from "@/services/user-routes";
import type { UserRoute } from "@/types/api";
import "../user-routes.scss";
import "../index.scss";

export default function UserRouteSquarePage() {
  const [items, setItems] = useState<UserRoute[]>([]); const [keyword, setKeyword] = useState(""); const [difficulty, setDifficulty] = useState<number>(); const [distance, setDistance] = useState<number>(); const [loading, setLoading] = useState(true);
  const load = async (filters: { difficulty?: number; distance?: number } = { difficulty, distance }) => { setLoading(true); try { const result = await userRouteService.publicList({ limit: 50, keyword: keyword.trim() || undefined, difficulty: filters.difficulty, max_distance: filters.distance }); setItems(result.items); } finally { setLoading(false); Taro.stopPullDownRefresh(); } };
  useDidShow(() => void load()); usePullDownRefresh(() => void load());
  return <View className="user-route-page"><Input className="user-route-search" value={keyword} placeholder="搜索标题、起点或终点" onInput={(e) => setKeyword(e.detail.value)} onConfirm={() => void load()} /><Text className="user-route-label">难度</Text><View className="user-route-tabs"><Text className={!difficulty ? "user-route-tab user-route-tab--active" : "user-route-tab"} onClick={() => { setDifficulty(undefined); void load({ difficulty: undefined, distance }); }}>全部</Text>{[1,2,3,4,5].map((value) => <Text key={value} className={difficulty === value ? "user-route-tab user-route-tab--active" : "user-route-tab"} onClick={() => { setDifficulty(value); void load({ difficulty: value, distance }); }}>{value}星</Text>)}</View><Text className="user-route-label">里程</Text><View className="user-route-tabs">{[[undefined,"不限"],[50,"50km内"],[100,"100km内"],[300,"300km内"]].map(([value,label]) => <Text key={label as string} className={distance === value ? "user-route-tab user-route-tab--active" : "user-route-tab"} onClick={() => { const next = value as number | undefined; setDistance(next); void load({ difficulty, distance: next }); }}>{label}</Text>)}</View>{loading ? <StatePanel type="loading" title="正在加载路线广场" /> : !items.length ? <StatePanel type="empty" title="没有匹配路线" /> : <View className="routes-page__list user-route-list">{items.map((route) => <View key={route.id} className="route-card" onClick={() => Taro.navigateTo({ url: `/pages/routes/detail/index?id=${route.id}` })}>{route.images[0] ? <Image className="route-card__cover" src={route.images[0]} mode="aspectFill" /> : <View className="route-card__cover route-card__cover--placeholder">用户路线</View>}<View className="route-card__body"><Text className="route-card__title">{route.title}</Text><Text className="route-card__meta">{route.start_location} → {route.end_location || "未设置终点"}</Text><Text className="route-card__summary">{route.description || `由 ${route.creator.nickname} 录入`}</Text><View className="route-card__facts"><Text>{route.total_distance != null ? `${route.total_distance} km` : "里程待补充"}</Text><Text>{route.estimated_time != null ? `约 ${route.estimated_time} 分钟` : "时长待补充"}</Text><Text className="route-card__favorite">{route.difficulty ? `${route.difficulty} 星` : "难度待补充"}</Text></View></View></View>)}</View>}</View>;
}
