import { Image, Input, Text, Textarea, View } from "@tarojs/components";
import Taro, { useLoad } from "@tarojs/taro";
import { useState } from "react";
import { userRouteService } from "@/services/user-routes";
import type { UserRoutePayload, UserRouteWaypoint } from "@/types/api";
import { uploadImage } from "@/utils/upload";
import "../user-routes.scss";

type LocationValue = { name: string; latitude: number; longitude: number };
export default function UserRouteCreatePage() {
  const [id, setId] = useState("");
  const [form, setForm] = useState({ title: "", description: "", start: undefined as LocationValue | undefined, end: undefined as LocationValue | undefined, waypoints: [] as UserRouteWaypoint[], distance: "", time: "", difficulty: 3, images: [] as string[], visibility: 1 as 1 | 2 });
  const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState(false);
  const update = <K extends keyof typeof form>(key: K, value: (typeof form)[K]) => setForm((current) => ({ ...current, [key]: value }));
  useLoad((options) => { if (options.id) { setId(options.id); void userRouteService.detail(options.id).then((route) => setForm({ title: route.title, description: route.description ?? "", start: { name: route.start_location, latitude: route.start_lat, longitude: route.start_lng }, end: route.end_location && route.end_lat != null && route.end_lng != null ? { name: route.end_location, latitude: route.end_lat, longitude: route.end_lng } : undefined, waypoints: route.waypoints, distance: route.total_distance?.toString() ?? "", time: route.estimated_time?.toString() ?? "", difficulty: route.difficulty ?? 3, images: route.images, visibility: route.visibility })); } });
  const chooseLocation = async (kind: "start" | "end" | "waypoint") => { try { const value = await Taro.chooseLocation({}); const location = { name: value.name || value.address, latitude: value.latitude, longitude: value.longitude }; if (kind === "waypoint") update("waypoints", [...form.waypoints, location]); else update(kind, location); } catch {} };
  const addImages = async () => { if (uploading) return; if (form.images.length >= 6) return void Taro.showToast({ title: "最多上传 6 张图片", icon: "none" }); try { const result = await Taro.chooseImage({ count: 6 - form.images.length, sizeType: ["compressed"], sourceType: ["album", "camera"] }); setUploading(true); const urls: string[] = []; for (const path of result.tempFilePaths) urls.push(await uploadImage(path, "image/jpeg", "user-routes")); update("images", [...form.images, ...urls].slice(0, 6)); } catch (error) { Taro.showToast({ title: error instanceof Error ? error.message : "上传失败", icon: "none" }); } finally { setUploading(false); } };
  const submit = async () => { if (saving || uploading) return; if (!form.title.trim() || !form.start) return void Taro.showToast({ title: "请填写标题并选择起点", icon: "none" }); if (form.visibility === 2) { const confirmed = await Taro.showModal({ title: "确认公开路线", content: "公开后，起点、终点和途经点的位置会向其他用户展示。请确认未填写家庭住址等敏感地点。", confirmText: "确认发布" }); if (!confirmed.confirm) return; } const payload: UserRoutePayload = { title: form.title.trim(), description: form.description.trim() || undefined, start_location: form.start.name, start_lat: form.start.latitude, start_lng: form.start.longitude, end_location: form.end?.name, end_lat: form.end?.latitude, end_lng: form.end?.longitude, waypoints: form.waypoints, total_distance: form.distance ? Number(form.distance) : undefined, estimated_time: form.time ? Number(form.time) : undefined, difficulty: form.difficulty, images: form.images, visibility: form.visibility }; setSaving(true); try { const route = id ? await userRouteService.update(id, payload) : await userRouteService.create(payload); Taro.showToast({ title: "保存成功", icon: "success" }); setTimeout(() => Taro.redirectTo({ url: `/pages/routes/detail/index?id=${route.id}` }), 500); } catch (error) { Taro.showToast({ title: error instanceof Error ? error.message : "保存失败", icon: "none" }); } finally { setSaving(false); } };
  return <View className="user-route-page"><View className="user-route-form__group"><Text className="user-route-title">{id ? "编辑路线" : "录入骑行路线"}</Text><Input className="user-route-form__input" value={form.title} maxlength={100} placeholder="路线标题（必填）" onInput={(e) => update("title", e.detail.value)} /><Textarea className="user-route-form__textarea" value={form.description} maxlength={5000} placeholder="路线描述" onInput={(e) => update("description", e.detail.value)} /><Text className="user-route-label">起终点</Text><View className="user-route-location" onClick={() => void chooseLocation("start")}>起点：{form.start?.name ?? "地图选点"}</View><View className="user-route-location" onClick={() => void chooseLocation("end")}>终点：{form.end?.name ?? "地图选点（选填）"}</View><Text className="user-route-label">途经点</Text>{form.waypoints.map((point, index) => <View key={`${point.name}-${index}`} className="user-route-location" onClick={() => update("waypoints", form.waypoints.filter((_, i) => i !== index))}>{point.name}（点击删除）</View>)}<View className="user-route-location" onClick={() => void chooseLocation("waypoint")}>+ 添加途经点</View><Input className="user-route-form__input" type="number" value={form.distance} placeholder="总里程（公里）" onInput={(e) => update("distance", e.detail.value)} /><Input className="user-route-form__input" type="number" value={form.time} placeholder="预计时长（分钟）" onInput={(e) => update("time", e.detail.value)} /><Text className="user-route-label">难度：{form.difficulty} 星</Text><View className="user-route-actions">{[1,2,3,4,5].map((value) => <Text key={value} className={form.difficulty === value ? "user-route-tab user-route-tab--active" : "user-route-tab"} onClick={() => update("difficulty", value)}>★{value}</Text>)}</View><Text className="user-route-label">路线图片（最多6张）</Text><View className="user-route-images">{form.images.map((url, index) => <View key={url} className="user-route-image-wrap"><Image className="user-route-image" src={url} mode="aspectFill" /><Text className="user-route-remove" onClick={() => update("images", form.images.filter((_, i) => i !== index))}>×</Text></View>)}</View><View className="user-route-location" onClick={() => void addImages()}>{uploading ? "上传中…" : "+ 选择图片或拍照"}</View><Text className="user-route-label">可见性</Text><View className="user-route-actions"><Text className={form.visibility === 1 ? "user-route-tab user-route-tab--active" : "user-route-tab"} onClick={() => update("visibility", 1)}>仅自己可见</Text><Text className={form.visibility === 2 ? "user-route-tab user-route-tab--active" : "user-route-tab"} onClick={() => update("visibility", 2)}>发布平台</Text></View>{form.visibility === 2 ? <Text className="user-route-meta">公开路线会展示所选点位，请勿填写家庭住址、单位等敏感地点。</Text> : null}</View><View className="user-route-submit" onClick={() => void submit()}>{saving ? "保存中…" : "保存路线"}</View></View>;
}
