import { DeleteOutlined, EyeOutlined, StopOutlined } from '@ant-design/icons';
import { Button, DatePicker, Form, Image, Input, Modal, Popconfirm, Select, Space, Table, Tag, message } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import dayjs from 'dayjs';
import { useCallback, useEffect, useState } from 'react';
import { adminApi } from '../api/admin';
import { useAuthStore } from '../stores/auth-store';
import type { ContentItem } from '../types';

const statusMap: Record<number, { text: string; color: string }> = { 0: { text: '已取消', color: 'default' }, 1: { text: '报名中', color: 'green' }, 2: { text: '即将开始', color: 'orange' }, 3: { text: '进行中', color: 'blue' }, 4: { text: '已结束', color: 'default' }, 5: { text: '已下架', color: 'red' } };
type Kind = 'ride' | 'activity';
export function ContentManagement({ kind }: { kind: Kind }) {
  const [form] = Form.useForm(); const [items, setItems] = useState<ContentItem[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const [selected, setSelected] = useState<ContentItem>(); const [loading, setLoading] = useState(false); const role = useAuthStore((x) => x.admin?.role);
  const load = useCallback(async (next = page) => { setLoading(true); try { const values = form.getFieldsValue(); const range = values.range as [dayjs.Dayjs, dayjs.Dayjs] | undefined; const params = { page: next, pageSize: 20, keyword: values.keyword || undefined, status: values.status, start_time: range?.[0]?.startOf('day').toISOString(), end_time: range?.[1]?.endOf('day').toISOString() }; const result = kind === 'ride' ? await adminApi.rides(params) : await adminApi.activities(params); setItems(result.list); setTotal(result.pagination.total); setPage(next); } finally { setLoading(false); } }, [form, kind, page]);
  useEffect(() => { void load(1); }, [kind]);
  const offline = async (id: string) => { if (kind === 'ride') await adminApi.offlineRide(id); else await adminApi.offlineActivity(id); message.success('已下架'); void load(); };
  const remove = async (id: string) => { if (kind === 'ride') await adminApi.deleteRide(id); else await adminApi.deleteActivity(id); message.success('已删除'); void load(); };
  const columns: ColumnsType<ContentItem> = [ ...(kind === 'activity' ? [{ title: '封面', dataIndex: 'cover_image', width: 88, render: (src: string | null) => src ? <Image width={52} height={40} style={{ objectFit: 'cover' }} src={src} /> : '-' }] : []), { title: 'ID', dataIndex: 'id', width: 90 }, { title: '标题', dataIndex: 'title', ellipsis: true }, { title: '发起人', render: (_, row) => row.creator.nickname }, { title: '状态', dataIndex: 'status', render: (value: number) => <Tag color={statusMap[value]?.color}>{statusMap[value]?.text || value}</Tag> }, ...(kind === 'ride' ? [{ title: '待复审', dataIndex: 'audit_status', render: (value?: number) => value === 0 ? <Tag color="gold">待复审</Tag> : '-' }] : []), { title: kind === 'ride' ? '报名人数' : '报名人数', render: (_, row) => kind === 'ride' ? (row.join_count ?? 0) : (row.register_count ?? 0) }, { title: kind === 'ride' ? '出发时间' : '开始时间', render: (_, row) => row.departure_time || row.start_time ? dayjs(row.departure_time || row.start_time).format('YYYY-MM-DD HH:mm') : '-' }, { title: '发布时间', dataIndex: 'created_at', render: (value: string) => dayjs(value).format('YYYY-MM-DD HH:mm') }, { title: '操作', width: 190, render: (_, row) => <Space size="small"><Button type="link" icon={<EyeOutlined />} onClick={() => setSelected(row)}>查看</Button><Popconfirm title="确定下架该内容？" onConfirm={() => void offline(row.id)}><Button type="link" danger icon={<StopOutlined />}>下架</Button></Popconfirm>{role === 9 && <Popconfirm title="删除不可恢复，确定继续？" onConfirm={() => void remove(row.id)}><Button type="link" danger icon={<DeleteOutlined />}>删除</Button></Popconfirm>}</Space> } ];
  return <><Form form={form} layout="inline" className="filter-bar" onFinish={() => void load(1)}><Form.Item name="keyword"><Input allowClear placeholder="标题 / 发起人" /></Form.Item><Form.Item name="status"><Select allowClear placeholder="全部状态" style={{ width: 128 }} options={Object.entries(statusMap).map(([value, item]) => ({ value: Number(value), label: item.text }))} /></Form.Item><Form.Item name="range"><DatePicker.RangePicker /></Form.Item><Button type="primary" htmlType="submit">查询</Button><Button onClick={() => { form.resetFields(); void load(1); }}>重置</Button></Form><Table className="page-card" rowKey="id" loading={loading} columns={columns} dataSource={items} pagination={{ current: page, total, pageSize: 20, onChange: (next) => void load(next) }} /><Modal open={Boolean(selected)} title={`${kind === 'ride' ? '约骑' : '活动'}详情`} footer={null} onCancel={() => setSelected(undefined)}><pre className="detail-json">{JSON.stringify(selected, null, 2)}</pre></Modal></>;
}
export const RidesPage = () => <ContentManagement kind="ride" />;
export const ActivitiesPage = () => <ContentManagement kind="activity" />;
