import { EyeOutlined } from '@ant-design/icons';
import { Button, Form, Input, Modal, Select, Space, Table, Tag, message } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import dayjs from 'dayjs'; import { useCallback, useEffect, useState } from 'react';
import { adminApi } from '../api/admin'; import type { ReportItem } from '../types';
const statuses = [{ value: 0, label: '待处理', color: 'gold' }, { value: 1, label: '已处理', color: 'green' }, { value: 2, label: '已忽略', color: 'default' }];
export function ReportsPage() { const [form] = Form.useForm(); const [items, setItems] = useState<ReportItem[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const [selected, setSelected] = useState<ReportItem>(); const [handling, setHandling] = useState<ReportItem>(); const [handleForm] = Form.useForm<{ action: 'offline' | 'ban' | 'ignore'; handling_note?: string }>();
 const load = useCallback(async (next = 1) => { const result = await adminApi.reports({ page: next, pageSize: 20, status: form.getFieldValue('status') }); setItems(result.list); setTotal(result.pagination.total); setPage(next); }, [form]); useEffect(() => { void load(1); }, [load]);
 const submitHandle = async (v: { action: 'offline' | 'ban' | 'ignore'; handling_note?: string }) => { if (!handling) return; await adminApi.handleReport(handling.id, v.action, v.handling_note); message.success('举报已处理'); setHandling(undefined); handleForm.resetFields(); void load(); };
 const columns: ColumnsType<ReportItem> = [{ title: '举报内容', render: (_, x) => `${x.content_type} #${x.content_id || '-'}` }, { title: '举报人', render: (_, x) => x.reporter.nickname }, { title: '被举报对象', render: (_, x) => x.reported_user?.nickname || `${x.content_type} 内容` }, { title: '原因', dataIndex: 'reason' }, { title: '状态', dataIndex: 'status', render: (x: number) => { const item = statuses.find((a) => a.value === x); return <Tag color={item?.color}>{item?.label}</Tag>; } }, { title: '时间', dataIndex: 'created_at', render: (x: string) => dayjs(x).format('YYYY-MM-DD HH:mm') }, { title: '操作', render: (_, x) => <Space><Button type="link" icon={<EyeOutlined />} onClick={() => setSelected(x)}>详情</Button>{x.status === 0 && <Button type="link" danger onClick={() => setHandling(x)}>处理</Button>}</Space> }];
 return <><Form className="filter-bar" form={form} layout="inline" onFinish={() => void load(1)}><Form.Item name="status"><Select allowClear placeholder="全部状态" style={{ width: 140 }} options={statuses.map(({ value, label }) => ({ value, label }))} /></Form.Item><Button type="primary" htmlType="submit">查询</Button><Button onClick={() => { form.resetFields(); void load(1); }}>重置</Button></Form><Table className="page-card" rowKey="id" columns={columns} dataSource={items} pagination={{ current: page, total, pageSize: 20, onChange: (x) => void load(x) }} /><Modal open={Boolean(selected)} title="举报详情" footer={null} onCancel={() => setSelected(undefined)}><pre className="detail-json">{JSON.stringify(selected, null, 2)}</pre></Modal><Modal open={Boolean(handling)} title="处理举报" onCancel={() => setHandling(undefined)} onOk={() => handleForm.submit()}><Form form={handleForm} layout="vertical" onFinish={submitHandle}><Form.Item name="action" label="处理方式" rules={[{ required: true, message: '请选择处理方式' }]}><Select options={[{ value: 'offline', label: '下架内容' }, { value: 'ban', label: '封禁用户' }, { value: 'ignore', label: '标记忽略' }]} /></Form.Item><Form.Item name="handling_note" label="处理备注"><Input.TextArea maxLength={500} /></Form.Item></Form></Modal></> }
