import { EyeOutlined, LockOutlined, UnlockOutlined } from '@ant-design/icons';
import { Avatar, Button, Descriptions, Form, Input, Modal, Popconfirm, Select, Space, Table, Tag, message } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import dayjs from 'dayjs'; import { useCallback, useEffect, useState } from 'react';
import { adminApi } from '../api/admin'; import { useAuthStore } from '../stores/auth-store'; import type { UserItem } from '../types';
export function UsersPage() { const [form] = Form.useForm(); const [items, setItems] = useState<UserItem[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const [detail, setDetail] = useState<Record<string, unknown>>(); const [reasonOpen, setReasonOpen] = useState<UserItem>(); const [reasonForm] = Form.useForm<{ reason: string }>(); const role = useAuthStore((x) => x.admin?.role); const canModify = role === 9;
 const load = useCallback(async (next = 1) => { const v = form.getFieldsValue(); const data = await adminApi.users({ page: next, pageSize: 20, keyword: v.keyword || undefined, status: v.status }); setItems(data.list); setTotal(data.pagination.total); setPage(next); }, [form]); useEffect(() => { void load(1); }, [load]);
 const detailUser = async (id: string) => setDetail(await adminApi.userDetail(id)); const unban = async (id: string) => { await adminApi.unbanUser(id); message.success('已解封'); void load(); }; const ban = async (value: { reason: string }) => { if (!reasonOpen) return; await adminApi.banUser(reasonOpen.id, value.reason); message.success('已封禁'); setReasonOpen(undefined); reasonForm.resetFields(); void load(); };
 const columns: ColumnsType<UserItem> = [{ title: '头像', dataIndex: 'avatar_url', width: 70, render: (x: string | null, row) => <Avatar src={x || undefined}>{row.nickname.slice(0, 1)}</Avatar> }, { title: '昵称', dataIndex: 'nickname' }, { title: '手机号', dataIndex: 'phone', render: (x) => x || '-' }, { title: '车型', dataIndex: 'motorcycle_model', render: (x) => x || '-' }, { title: '状态', dataIndex: 'status', render: (x) => <Tag color={x === 1 ? 'green' : 'red'}>{x === 1 ? '正常' : '已封禁'}</Tag> }, { title: '注册时间', dataIndex: 'created_at', render: (x: string) => dayjs(x).format('YYYY-MM-DD HH:mm') }, { title: '操作', render: (_, row) => <Space><Button type="link" icon={<EyeOutlined />} onClick={() => void detailUser(row.id)}>详情</Button>{canModify && (row.status === 1 ? <Button type="link" danger icon={<LockOutlined />} onClick={() => setReasonOpen(row)}>封禁</Button> : <Popconfirm title="确认解封该用户？" onConfirm={() => void unban(row.id)}><Button type="link" icon={<UnlockOutlined />}>解封</Button></Popconfirm>)}</Space> }];
 return <><Form className="filter-bar" form={form} layout="inline" onFinish={() => void load(1)}><Form.Item name="keyword"><Input allowClear placeholder="昵称 / 手机号" /></Form.Item><Form.Item name="status"><Select allowClear placeholder="全部状态" style={{ width: 120 }} options={[{ value: 1, label: '正常' }, { value: 0, label: '已封禁' }]} /></Form.Item><Button type="primary" htmlType="submit">查询</Button><Button onClick={() => { form.resetFields(); void load(1); }}>重置</Button></Form><Table className="page-card" rowKey="id" columns={columns} dataSource={items} pagination={{ current: page, total, pageSize: 20, onChange: (x) => void load(x) }} /><Modal open={Boolean(detail)} title="用户详情" footer={null} onCancel={() => setDetail(undefined)}><Descriptions column={1} bordered size="small">{detail && Object.entries(detail).filter(([key]) => key !== 'profile').map(([key, value]) => <Descriptions.Item key={key} label={key}>{typeof value === 'object' ? JSON.stringify(value) : String(value ?? '-')}</Descriptions.Item>)}</Descriptions></Modal><Modal open={Boolean(reasonOpen)} title={`封禁 ${reasonOpen?.nickname || ''}`} onCancel={() => setReasonOpen(undefined)} onOk={() => reasonForm.submit()}><Form form={reasonForm} layout="vertical" onFinish={ban}><Form.Item name="reason" label="封禁原因" rules={[{ required: true, message: '请填写封禁原因' }]}><Input.TextArea maxLength={500} /></Form.Item></Form></Modal></> }
