import { request } from './client';
import type { AdminUser, ContentItem, FeatureFlagSettings, ListResult, MetricsSnapshot, RegulationFeedbackItem, RegulationImportListItem, RegulationImportTask, RegulationItem, RegulationPayload, ReportItem, RouteCommentAdminItem, RouteItem, RoutePayload, SafetyAgreementAdminItem, SafetyGuideAdminItem, SafetyGuideRevisionPayload, TaskFailureItem, TrendItem, UpdateFeatureFlagSettings, UserItem } from '../types';

export const adminApi = {
  login: (username: string, password: string) => request<{ access_token: string; admin: AdminUser }>({ method: 'POST', url: '/admin/auth/login', data: { username, password } }),
  rides: (params: Record<string, unknown>) => request<ListResult<ContentItem>>({ url: '/admin/rides', params }),
  offlineRide: (id: string) => request<void>({ method: 'POST', url: `/admin/rides/${id}/offline` }),
  deleteRide: (id: string) => request<void>({ method: 'DELETE', url: `/admin/rides/${id}` }),
  users: (params: Record<string, unknown>) => request<ListResult<UserItem>>({ url: '/admin/users', params }),
  userDetail: (id: string) => request<Record<string, unknown>>({ url: `/admin/users/${id}` }),
  banUser: (id: string, reason: string) => request<void>({ method: 'POST', url: `/admin/users/${id}/ban`, data: { reason } }),
  unbanUser: (id: string) => request<void>({ method: 'POST', url: `/admin/users/${id}/unban` }),
  overview: () => request<{ total_users: number; dau: number; today_new_users: number; total_rides: number }>({ url: '/admin/stats/overview' }),
  trend: (days: 7 | 30) => request<{ list: TrendItem[] }>({ url: '/admin/stats/trend', params: { days } }),
  reports: (params: Record<string, unknown>) => request<ListResult<ReportItem>>({ url: '/admin/reports', params }),
  handleReport: (id: string, action: 'offline' | 'ban' | 'ignore', handling_note?: string) => request<void>({ method: 'POST', url: `/admin/reports/${id}/handle`, data: { action, handling_note } }),
  routes: (params: Record<string, unknown>) => request<ListResult<RouteItem>>({ url: '/admin/routes', params }),
  route: (id: string) => request<RouteItem>({ url: `/admin/routes/${id}` }),
  createRoute: (data: RoutePayload) => request<RouteItem>({ method: 'POST', url: '/admin/routes', data }),
  updateRoute: (id: string, data: RoutePayload) => request<RouteItem>({ method: 'PATCH', url: `/admin/routes/${id}`, data }),
  publishRoute: (id: string) => request<RouteItem>({ method: 'POST', url: `/admin/routes/${id}/publish` }),
  offlineRoute: (id: string, reason: string) => request<RouteItem>({ method: 'POST', url: `/admin/routes/${id}/offline`, data: { reason } }),
  regulations: (params: Record<string, unknown>) => request<ListResult<RegulationItem>>({ url: '/admin/regulations', params }),
  regulation: (id: string) => request<RegulationItem>({ url: `/admin/regulations/${id}` }),
  createRegulation: (data: RegulationPayload) => request<{ id: string }>({ method: 'POST', url: '/admin/regulations', data }),
  updateRegulation: (id: string, data: Partial<RegulationPayload>) => request<{ id: string }>({ method: 'PATCH', url: `/admin/regulations/${id}`, data }),
  submitRegulationReview: (id: string, reason: string) => request<void>({ method: 'POST', url: `/admin/regulations/${id}/submit-review`, data: { reason } }),
  batchSubmitRegulationReview: (ids: string[], reason: string) => request<{ count: number; ids: string[] }>({ method: 'POST', url: '/admin/regulations/batch/submit-review', data: { ids, reason } }),
  reviewRegulation: (id: string, reason: string) => request<void>({ method: 'POST', url: `/admin/regulations/${id}/review`, data: { reason } }),
  batchReviewRegulations: (ids: string[], reason: string) => request<{ count: number; ids: string[] }>({ method: 'POST', url: '/admin/regulations/batch/review', data: { ids, reason } }),
  publishRegulation: (id: string, reason: string) => request<void>({ method: 'POST', url: `/admin/regulations/${id}/publish`, data: { reason } }),
  batchPublishRegulations: (ids: string[], reason: string) => request<{ count: number; ids: string[] }>({ method: 'POST', url: '/admin/regulations/batch/publish', data: { ids, reason } }),
  expireRegulation: (id: string, data: { reason: string; expired_at?: string; replacement_regulation_id?: string }) => request<void>({ method: 'POST', url: `/admin/regulations/${id}/expire`, data }),
  replaceRegulation: (id: string, data: { reason: string; replacement_regulation_id: string }) => request<void>({ method: 'POST', url: `/admin/regulations/${id}/replace`, data }),
  offlineRegulation: (id: string, reason: string) => request<void>({ method: 'POST', url: `/admin/regulations/${id}/offline`, data: { reason } }),
  deleteRegulation: (id: string, reason: string) => request<{ count: number; ids: string[] }>({ method: 'DELETE', url: `/admin/regulations/${id}`, data: { reason } }),
  batchDeleteRegulations: (ids: string[], reason: string) => request<{ count: number; ids: string[] }>({ method: 'POST', url: '/admin/regulations/batch/delete', data: { ids, reason } }),
  previewRegulationImport: (file: File, idempotencyKey: string) => {
    const data = new FormData(); data.append('file', file);
    return request<RegulationImportTask>({ method: 'POST', url: '/admin/regulations/imports', data, headers: { 'Idempotency-Key': idempotencyKey } });
  },
  confirmRegulationImport: (id: string, reason: string) => request<{ imported_count: number; replayed: boolean }>({ method: 'POST', url: `/admin/regulations/imports/${id}/confirm`, data: { reason } }),
  regulationImports: (params: Record<string, unknown>) => request<ListResult<RegulationImportListItem>>({ url: '/admin/regulations/imports', params }),
  regulationFeedbacks: (params: Record<string, unknown>) => request<ListResult<RegulationFeedbackItem>>({ url: '/admin/regulations/feedbacks', params }),
  resolveRegulationFeedback: (id: string, reason: string) => request<void>({ method: 'POST', url: `/admin/regulations/feedbacks/${id}/resolve`, data: { reason } }),
  metrics: () => request<MetricsSnapshot>({ url: '/admin/observability/metrics' }),
  taskFailures: (params: Record<string, unknown>) => request<ListResult<TaskFailureItem>>({ url: '/admin/maintenance/task-failures', params }),
  retryTaskFailure: (id: string) => request<void>({ method: 'POST', url: `/admin/maintenance/task-failures/${id}/retry` }),
  resolveTaskFailure: (id: string, note: string) => request<void>({ method: 'POST', url: `/admin/maintenance/task-failures/${id}/resolve`, data: { note } }),
  reconcileCounters: (note: string) => request<{ routes: number; total: number }>({ method: 'POST', url: '/admin/maintenance/counters/reconcile', data: { note } }),
  featureFlags: () => request<FeatureFlagSettings>({ url: '/admin/feature-flags' }),
  updateFeatureFlags: (data: UpdateFeatureFlagSettings) => request<FeatureFlagSettings>({ method: 'PATCH', url: '/admin/feature-flags', data }),
  routeComments: (params: Record<string, unknown>) => request<ListResult<RouteCommentAdminItem>>({ url: '/admin/route-comments', params }),
  deleteRouteComment: (id: string, reason: string) => request<void>({ method: 'DELETE', url: `/admin/route-comments/${id}`, data: { reason } }),
  safetyGuides: () => request<SafetyGuideAdminItem[]>({ url: '/admin/safety-guides' }),
  createSafetyGuideRevision: (data: SafetyGuideRevisionPayload) => request<{ id: string }>({ method: 'POST', url: '/admin/safety-guides/revisions', data }),
  reviewSafetyGuide: (id: string, reason: string) => request<void>({ method: 'POST', url: `/admin/safety-guides/revisions/${id}/review`, data: { reason } }),
  publishSafetyGuide: (id: string, reason: string) => request<void>({ method: 'POST', url: `/admin/safety-guides/revisions/${id}/publish`, data: { reason } }),
  safetyAgreements: () => request<SafetyAgreementAdminItem[]>({ url: '/admin/safety-agreements' }),
  createSafetyAgreement: (data: Record<string, unknown>) => request<Array<{ id: string }>>({ method: 'POST', url: '/admin/safety-agreements', data }),
  reviewSafetyAgreement: (id: string, reason: string) => request<void>({ method: 'POST', url: `/admin/safety-agreements/${id}/review`, data: { reason } }),
  publishSafetyAgreement: (id: string, reason: string) => request<void>({ method: 'POST', url: `/admin/safety-agreements/${id}/publish`, data: { reason } }),
};
